server:
    port: 8080
    servlet:
        context-path: /farmstory

spring:
    application:
        name: farmstory
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Password1!
        url: jdbc:mysql://43.200.184.246/farmstory_4
        username: abc1234

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
                    naver:
                        authorization-uri : https://nid.naver.com/oauth2.0/authorize?prompt=login
                        user_name_attribute: response
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me

                registration:
                    kakao:
                        client-name: kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/kakao
                        client-id: f4f4a541f1f5bfb22fe74399fb26d44a
                        client-secret: R6wHsQNPhmR40afxadEqnfb3kJrnidyH
                        client-authentication-method: client_secret_post
                        scope: profile_nickname, profile_image
                    google:
                        client-id: 357787742243-sq5srl2rk7qeq1l0bdc51igg6b4g2an0.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/farmstory/login/oauth2/code/google
                        scope:
                            - email
                            - profile
                    naver:
                        client-name: naver
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-id: XAIYzlm6pgTUrsvvVz8P
                        client-secret: r_IphLfimA
                        redirect-uri: http://localhost:8080/sboard/login/oauth2/code/naver
                        scope: email, nickname, name



    mail:
        host: smtp.gmail.com
        port: 587
        username: gahui446@gmail.com
        password: zodwmccixsuayezm
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true


    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    thymeleaf:
        prefix: classpath:/templates

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

logging:
    file:
        name: logs/farmstory.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

jwt:
    issuer: gahui446@gmail.com
    secret: eYgN3XAUp6AOJ089Il8TljMbX1W7KARC

file:
    upload:
        path: uploads/
